/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names, unused_field

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData solution2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData surface1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData surface2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData _f = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData balcony = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bathtube = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed__1_ = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bed = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulb = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circles = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData furniture_and_household = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_38 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_awesome_power_off = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_feather_home = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_feather_settings = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_ionic_md_arrow_round_back = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kitchen = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_bulb = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData room = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solution = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solution1 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
